name: Syft SBOM Generation

on:
  push:
    branches:
      - develop  # Adjust this according to your branch naming

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: CISA-SBOM/Testing-untitledgoosetool
          ref: main  # or whatever branch you want to use

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      - name: Generate SBOM
        run: |
          syft -o sbom.json .

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: syft-sbom
          path: sbom.json
