name: Move Scan

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  
env:
  OUTPUT_ARTIFACT_WORK_DIR: /tmp/output-artifact-work

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Generate SPDX JSON
        id: spdx
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json

      - name: Upload SPDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: SPDX-Scan-Results
          path: ${{ steps.spdx.outputs.artifact_path }}

      - name: Clone repo to move artifacts
        uses: actions/checkout@v2
        with:
          repository: CISA-SBOM/Testing-untitledgoosetool
          ref: develop
          path: cloned_repo

      - name: Move SPDX JSON to specified path
        run: |
          if [ -f "$GITHUB_WORKSPACE/${{ steps.spdx.outputs.artifact_path }}" ]; then
            mv "$GITHUB_WORKSPACE/${{ steps.spdx.outputs.artifact_path }}" "$GITHUB_WORKSPACE/cloned_repo/SBOM/"
          else
            echo "SPDX JSON file not found."
            exit 1
          fi

      - name: Move CycloneDX JSON to specified path
        run: mv cdx.json $GITHUB_WORKSPACE/cloned_repo/SBOM/

      - name: Commit and push changes
        run: |
          cd $GITHUB_WORKSPACE/cloned_repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Upload SPDX and CycloneDX JSON files"
          git push
