name: MOVE Scan

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  
jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: spdx
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json

      - name: cdx
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json

      - name: Move artifacts to SBOM folder
        run: |
          mkdir -p SBOM
          mv spdx.json SBOM/
          mv cdx.json SBOM/

      - name: Commit and push SBOM artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add SBOM/
          git commit -m "Add SBOM artifacts"
          git push
