name: Move Scan

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Generate SPDX JSON
        id: spdx
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json

      - name: Generate CycloneDX JSON
        id: cdx
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json

      - name: Upload SPDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: SPDX-Scan-Results
          path: ${{ steps.spdx.outputs.artifact-path }}

      - name: Upload CycloneDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: CycloneDX-Scan-Results
          path: ${{ steps.cdx.outputs.artifact-path }}
