name: SBOM Scan

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  
jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: spdx
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json

      - name: cdx
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json

      # Move generated artifacts to the root directory
      - name: Move SBOM Artifacts
        run: |
          mv spdx.json $GITHUB_WORKSPACE
          mv cdx.json $GITHUB_WORKSPACE

      # Commit and push artifacts to the repository
      - name: Commit and Push SBOM Artifacts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add SBOM artifacts
