name: Move Scan

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  
env:
  OUTPUT_ARTIFACT_WORK_DIR: /tmp/output-artifact-work

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: spdx
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx.json

      - name: cdx
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: cdx.json

      - name: Upload SPDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: SPDX-Scan-Results
          path: spdx.json

      - name: Upload CycloneDX JSON
        uses: actions/upload-artifact@v2
        with:
          name: CycloneDX-Scan-Results
          path: cdx.json

      - name: Clone repo to move artifacts
        uses: actions/checkout@v2
        with:
          repository: CISA-SBOM/Testing-untitledgoosetool
          ref: develop
          path: cloned_repo

      - name: Move SPDX JSON to specified path
        run: mv spdx.json cloned_repo/SBOM/

      - name: Move CycloneDX JSON to specified path
        run: mv cdx.json cloned_repo/SBOM/

      - name: Commit and push changes
        run: |
          cd cloned_repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Upload SPDX and CycloneDX JSON files"
          git push
